blank_issues_enabled: false
contact_links:
  - name: "ðŸ¤” Question and Help"
    url: https://github.com/strongswan/strongswan/discussions
    about: Questions should go to the strongSwan community's help and discussion forum. GitHub issues are for bug reports and feature suggestions
  - name: "ðŸ“– Documentation"
    url: https://github.com/strongswan/strongswan-docs/issues
    about: Suggest improvements or report errors regarding https://docs.strongswan.org
