name: Android

on: [push, pull_request]

env:
  CCACHE_BASEDIR: ${{ github.workspace }}
  CCACHE_COMPRESS: true
  CCACHE_MAXSIZE: 400M
  CC: gcc
  OS_NAME: linux

jobs:
  pre-check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip-check.outputs.should_skip }}
    steps:
      - id: skip-check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'

  android:
    needs: pre-check
    if: ${{ needs.pre-check.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    env:
      TEST: android
      # since the NDK is newly installed every time, we have to use this to avoid cache misses
      CCACHE_COMPILERCHECK: content
    steps:
      # we currently don't specify a specific NDK version in our gradle files,
      # so we load the version the Gradle Plugin uses as default but which is
      # not installed anymore in the image
      - name: Install NDK
        run: yes | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install 'ndk;21.4.7075529'
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.cache/ccache
          key: ccache-android-${{ github.sha }}
          restore-keys: |
            ccache-android-
      - run: |
          sudo apt-get install -qq ccache
          echo "PATH=/usr/lib/ccache:$PATH" >> $GITHUB_ENV
          ccache -z
      - uses: ./.github/actions/default
      - run: ccache -s
      - uses: actions/upload-artifact@v3
        with:
          name: Lint Results
          path: src/frontends/android/app/build/reports/lint-results.xml
